### ISSUE TITLE
[webpack-cli] HookWebpackError: inputSource.sourceAndMap is not a function

### ISSUE THREAD

**Issue by HwangTaehyun** [Yuan-Yiming/remove-console-webpack-plugin#1]
When I add this plugin to my project, it throws the following error!
```
[webpack-cli] HookWebpackError: inputSource.sourceAndMap is not a function
```

**Comment by Yuan-Yiming** [comment]
您好，我是袁艺明，您的邮件我已经收到了，我会尽快查看的！

**Comment by yuan-yiming** [comment]
> When I add this plugin to my project, it throws the following error!
> 
> ```
> [webpack-cli] HookWebpackError: inputSource.sourceAndMap is not a function
> ```

What's your webpack's version? This plugin is only supported in  webpack 4 or 5.

**Comment by matt-resto-guru** [comment]
I have the same issue with webpack 5

**Comment by matt-resto-guru** [comment]
This fix works for me, though I'm honestly not sure if it's correct or not

![remove-console-fix](https://user-images.githubusercontent.com/66277813/169290574-a0952d8c-81f4-42b9-aaac-e281c7c270c7.png)

**Comment by Diae-Louali** [comment]
Has anyone found a solution to this ?  Webpack version is : "^5.59.1".

It happens when my webpack mode is production.

**Comment by aj502gm** [comment]
this does not works.

**Comment by nadee-org** [comment]
Breaks in Webpack 5.72.* as well. Is this plugin maintained anymore?

**Comment by HwangTaehyun** [comment]
@matt-resto-guru @Diae-Louali @aj502gm @Nadeeshyama 
I share my webpack's prod config to remove console.

Use https://github.com/webpack-contrib/terser-webpack-plugin#terseroptions plugin.

```
...
    mode: 'production',
    entry: {
      index: './src/renderer/index.tsx',
    },
    output: {
      path: path.resolve(__dirname, OUT_DIR),
      filename: '[name].js',
    },
    optimization: {
      minimize: true,
      minimizer: [
        new TerserPlugin({
          test: /\.js(\?.*)?$/i,
          extractComments: false,
          terserOptions: {
            compress: {
              drop_console: true,
              drop_debugger: true,
              pure_funcs: ['console.log', 'console.info'], // Delete console
            },
          },
        }),
      ],
    },
...
```

I will close this issue.
